/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farmmanagement;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author yusuf
 */
public class AnimalScreen extends javax.swing.JDialog {
    DefaultTableModel model;
    AnimalTransactions transaction=new AnimalTransactions();
    FarmCase farmCase = new FarmCase();
    /**
     * Creates new form AnimalScreen
     */
    public AnimalScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model=(DefaultTableModel)animalTable.getModel();
        viewAnimal();
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() { 
            Long startTime = System.currentTimeMillis();
               for (int i=0;i<1000;i++){
                   System.out.println("Threde girdim.");
                    try {
                        Thread.sleep(1000);
                        for(Animal a : transaction.bringAnimals()){
                            System.out.println("Ben i :" + i);
                            a.setProduct_status(1+a.getProduct_status());
                            if(a.getYasamSuresi() < (System.currentTimeMillis()-startTime)/1000){
                                transaction.deleteAnimal(a.getId());
                                System.out.println(a.getId() + " " +a.getYasamSuresi()); 
                                viewAnimal();
                            }
                            System.out.println(a.getProduct_status());
                            System.out.println(farmCase.getMilk());
                            if(a.getProduct_status() > (100*a.getDeliveryTimeRandom())){
                             farmCase.setMilk(i);
                              System.out.println("Kasamdaki süt sayısı : " + farmCase.getMilk());
                            if(a.getType().equals("Cow")){
                                
                            }
                             a.setProduct_status(1);
                        }
                        }
                    } catch (Exception ex) {
                        System.out.println("HATAAA!" + ex.getMessage());
                        Logger.getLogger(ProgressBarScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                }
            }
          
        
        
       
        
        
    });
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        animalTable = new javax.swing.JTable();
        searchbutton = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeLine = new javax.swing.JTextField();
        genderLine = new javax.swing.JTextField();
        ageLine = new javax.swing.JTextField();
        productLine = new javax.swing.JTextField();
        addAnimal = new javax.swing.JButton();
        productStatusLabel = new javax.swing.JLabel();
        productStatusLine = new javax.swing.JTextField();
        deleteAnimal = new javax.swing.JButton();
        informationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        animalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Tür", "Cinsiyet", "Yaş", "Üretim Ürün", "Üretim Durumu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(animalTable);
        if (animalTable.getColumnModel().getColumnCount() > 0) {
            animalTable.getColumnModel().getColumn(0).setResizable(false);
            animalTable.getColumnModel().getColumn(1).setResizable(false);
            animalTable.getColumnModel().getColumn(2).setResizable(false);
            animalTable.getColumnModel().getColumn(3).setResizable(false);
            animalTable.getColumnModel().getColumn(4).setResizable(false);
            animalTable.getColumnModel().getColumn(5).setResizable(false);
        }

        searchbutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbuttonKeyReleased(evt);
            }
        });

        jLabel1.setText("Tür :");

        jLabel2.setText("Cinsiyet :");

        jLabel3.setText("Yaş :");

        jLabel4.setText("Ürün :");

        addAnimal.setText("Hayvan Ekle");
        addAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnimalActionPerformed(evt);
            }
        });

        productStatusLabel.setText("Üretim Durumu :");

        deleteAnimal.setText("Hayvan Sil");
        deleteAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAnimalActionPerformed(evt);
            }
        });

        informationButton.setText("Detaylı Bilgi");
        informationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchbutton)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeLine, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(genderLine)
                            .addComponent(ageLine)
                            .addComponent(productLine))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(productStatusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productStatusLine)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(deleteAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(informationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(typeLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAnimal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(genderLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAnimal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(ageLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(informationButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(productLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productStatusLabel)
                    .addComponent(productStatusLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void dynamicSearch(String search){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        
        animalTable.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(search));
    }
    private void searchbuttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbuttonKeyReleased
        String search=searchbutton.getText();
        dynamicSearch(search);
    }//GEN-LAST:event_searchbuttonKeyReleased

    private void addAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnimalActionPerformed
       String type=typeLine.getText();
       String gender=genderLine.getText();
       String product= productLine.getText();
       String product_status= productStatusLine.getText();
       String age=ageLine.getText();
       
       transaction.addAnimal(type,gender,age,product,product_status);
       viewAnimal();
       
    }//GEN-LAST:event_addAnimalActionPerformed

    private void deleteAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAnimalActionPerformed
        int selectedRow=animalTable.getSelectedRow();
        int id= (int) model.getValueAt(selectedRow, 0);
        transaction.deleteAnimal(id);
        viewAnimal();
        
    }//GEN-LAST:event_deleteAnimalActionPerformed

    private void informationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationButtonActionPerformed
            int selectedRow=animalTable.getSelectedRow();
            int deliveryTime= (int) model.getValueAt(selectedRow, 5);
            Animal animal = transaction.bringAnimals().get(selectedRow);
            //System.out.println(transaction.bringAnimals().get(selectedRow).getAge());
           
            //System.out.println(deliveryTime);
           ProgressBarScreen progressbar1 = new ProgressBarScreen(animal);
            
            setVisible(false);
            
            //progressbar1.setVisible(true);
            //InformationPage.fill(deliveryTime);
            
            progressbar1.setVisible(true);
            
                // TODO add your handling code here:
    }//GEN-LAST:event_informationButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public void viewAnimal(){
        model.setRowCount(0);
        ArrayList<Animal> animals= new ArrayList<Animal>();
        
        animals=transaction.bringAnimals();
        if (animals != null){
            for (Animal animal:animals){
                Object[] add={animal.getId(),animal.getType(),animal.getGender(),animal.getAge(),animal.getProduct(),animal.getProduct_status()};
                model.addRow(add);
            }
        }
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAnimal;
    private javax.swing.JTextField ageLine;
    private javax.swing.JTable animalTable;
    private javax.swing.JButton deleteAnimal;
    private javax.swing.JTextField genderLine;
    private javax.swing.JButton informationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField productLine;
    private javax.swing.JLabel productStatusLabel;
    private javax.swing.JTextField productStatusLine;
    private javax.swing.JTextField searchbutton;
    private javax.swing.JTextField typeLine;
    // End of variables declaration//GEN-END:variables
}
