/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmmanagement;

import com.mysql.cj.x.protobuf.MysqlxNotice;
import java.awt.Component;
import java.awt.image.ComponentColorModel;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yusuf
 */
public class ProgressBarScreen extends javax.swing.JFrame {

    /**
     * Creates new form ProgressBarScreen
     */
    public ProgressBarScreen(Animal animal) {
        
        initComponents();
      
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //Random delivery=new Random();
                //int delivertime=delivery.nextInt(200)+350;
               int deliveryTimeRandom = animal.getDeliveryTimeRandom();
               int deliveryTime = animal.getProduct_status();
               while(true){
                   try {
                       progressBar1.setValue(deliveryTime);
                       Thread.sleep(deliveryTimeRandom*1000);
                   } catch (InterruptedException ex) {
                       Logger.getLogger(ProgressBarScreen.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   deliveryTime++;
                   if(deliveryTime > 100){
                       animal.setProduct_status(deliveryTime%100);
                       deliveryTime = deliveryTime%100;
                       if(animal.getType().equals("inek")){
                           Done.setText(animal.getProduct()+" Deponuza Eklendi.");
                         FarmCase.addMilk(1);
                       }else if(animal.getType().equals("Ari")){
                           Done.setText(animal.getProduct()+" Deponuza Eklendi.");
                            FarmCase.addHoney(1);
                       }else{
                           Done.setText(animal.getProduct()+" Deponuza Eklendi.");
                            FarmCase.addEgg(1);
                      }
                       
                       
                       
                   }
                   if(deliveryTime==5){
                       Done.setText("Ürün Üretiliyor");
                   }
               }
               
               
               /*for (int i=deliveryTime;i<100;i++){
                   
                    try {
                        progressBar1.setValue(i); 
                        Thread.sleep(deliveryTimeRandom);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ProgressBarScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                }*/
            }
          
        
        
       
        
        
    });
        t.start();
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar1 = new javax.swing.JProgressBar();
        Back = new javax.swing.JButton();
        Done = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setText("Geri ");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Done.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Done.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ÜRETİM SÜRECİ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(530, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Done, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(progressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Done, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.dispose();
       AnimalScreen.key = true;
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Done;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JProgressBar progressBar1;
    // End of variables declaration//GEN-END:variables
}
